#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Droid.Resource", IsApplication=true)]

namespace Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Acr.MvvmCross.Plugins.BarCodeScanner.Droid.Resource.Id.contentFrame = global::Sample.Droid.Resource.Id.contentFrame;
			global::Acr.MvvmCross.Plugins.BarCodeScanner.Droid.Resource.Layout.zxingscanneractivitylayout = global::Sample.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::Acr.MvvmCross.Plugins.BarCodeScanner.Droid.Resource.Layout.zxingscannerfragmentlayout = global::Sample.Droid.Resource.Layout.zxingscannerfragmentlayout;
			global::Acr.MvvmCross.Plugins.BarCodeScanner.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.BarCodeScanner.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.DeviceInfo.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.DeviceInfo.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.FileSystem.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.FileSystem.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.Network.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.Network.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.Settings.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.Settings.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.SignaturePad.Droid.Resource.Id.btnCancel = global::Sample.Droid.Resource.Id.btnCancel;
			global::Acr.MvvmCross.Plugins.SignaturePad.Droid.Resource.Id.btnSave = global::Sample.Droid.Resource.Id.btnSave;
			global::Acr.MvvmCross.Plugins.SignaturePad.Droid.Resource.Id.rootView = global::Sample.Droid.Resource.Id.rootView;
			global::Acr.MvvmCross.Plugins.SignaturePad.Droid.Resource.Id.signatureView = global::Sample.Droid.Resource.Id.signatureView;
			global::Acr.MvvmCross.Plugins.SignaturePad.Droid.Resource.Layout.SignaturePad = global::Sample.Droid.Resource.Layout.SignaturePad;
			global::Acr.MvvmCross.Plugins.SignaturePad.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.SignaturePad.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahBarColor = global::Sample.Droid.Resource.Attribute.ahBarColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahBarLength = global::Sample.Droid.Resource.Attribute.ahBarLength;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahBarWidth = global::Sample.Droid.Resource.Attribute.ahBarWidth;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahCircleColor = global::Sample.Droid.Resource.Attribute.ahCircleColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahDelayMillis = global::Sample.Droid.Resource.Attribute.ahDelayMillis;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahRadius = global::Sample.Droid.Resource.Attribute.ahRadius;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahRimColor = global::Sample.Droid.Resource.Attribute.ahRimColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahRimWidth = global::Sample.Droid.Resource.Attribute.ahRimWidth;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahSpinSpeed = global::Sample.Droid.Resource.Attribute.ahSpinSpeed;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahText = global::Sample.Droid.Resource.Attribute.ahText;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahTextColor = global::Sample.Droid.Resource.Attribute.ahTextColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.ahTextSize = global::Sample.Droid.Resource.Attribute.ahTextSize;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Drawable.ic_errorstatus = global::Sample.Droid.Resource.Drawable.ic_errorstatus;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Drawable.ic_successstatus = global::Sample.Droid.Resource.Drawable.ic_successstatus;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Drawable.roundedbg = global::Sample.Droid.Resource.Drawable.roundedbg;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Drawable.roundedbgdark = global::Sample.Droid.Resource.Drawable.roundedbgdark;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Id.loadingImage = global::Sample.Droid.Resource.Id.loadingImage;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Id.loadingProgressBar = global::Sample.Droid.Resource.Id.loadingProgressBar;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Id.loadingProgressWheel = global::Sample.Droid.Resource.Id.loadingProgressWheel;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Id.textViewStatus = global::Sample.Droid.Resource.Id.textViewStatus;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Layout.loading = global::Sample.Droid.Resource.Layout.loading;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Layout.loadingimage = global::Sample.Droid.Resource.Layout.loadingimage;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Layout.loadingprogress = global::Sample.Droid.Resource.Layout.loadingprogress;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.String.library_name = global::Sample.Droid.Resource.String.library_name;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel = global::Sample.Droid.Resource.Styleable.ProgressWheel;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarLength = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahBarWidth = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahCircleColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRadius = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRimColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahRimWidth = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahText = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahTextColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_ahTextSize = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::Sample.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::Sample.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::Sample.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::Sample.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::Sample.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::Sample.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::Sample.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::Sample.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::Sample.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::Sample.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::Sample.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::Sample.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::Sample.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::Sample.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::Sample.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::Sample.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::Sample.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::Sample.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::Sample.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::Sample.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::Sample.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::Sample.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::Sample.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::Sample.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::Sample.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::Sample.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Sample.Droid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Sample.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Sample.Droid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000c
			public const int MvxBind = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int MvxDropDownItemTemplate = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int MvxItemTemplate = 2130771983;
			
			// aapt resource value: 0x7f01000d
			public const int MvxLang = 2130771981;
			
			// aapt resource value: 0x7f010011
			public const int MvxSource = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int MvxTemplate = 2130771982;
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_errorstatus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_successstatus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int roundedbg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int roundedbgdark = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int btnCancel = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int btnSave = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int contentFrame = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int loadingImage = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int loadingProgressBar = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int loadingProgressWheel = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int rootView = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int signatureView = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int textViewStatus = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BarCode = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BarCodeCreate = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DeviceInfo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Dialogs = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Home = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int HomeListItem = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int loading = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int loadingimage = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int loadingprogress = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Network = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Settings = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SettingsListItem = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int SignatureConfiguration = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int SignatureList = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int SignatureListItem = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SignaturePad = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int SpinnerColorDefinition = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Splash = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int zxingscanneractivitylayout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int zxingscannerfragmentlayout = 2130903059;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771980,
					2130771981};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771982};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771985};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
