#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Droid.Resource", IsApplication=true)]

namespace Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.barColor = global::Sample.Droid.Resource.Attribute.barColor;
			global::AndroidHUD.Resource.Attribute.barLength = global::Sample.Droid.Resource.Attribute.barLength;
			global::AndroidHUD.Resource.Attribute.barWidth = global::Sample.Droid.Resource.Attribute.barWidth;
			global::AndroidHUD.Resource.Attribute.circleColor = global::Sample.Droid.Resource.Attribute.circleColor;
			global::AndroidHUD.Resource.Attribute.delayMillis = global::Sample.Droid.Resource.Attribute.delayMillis;
			global::AndroidHUD.Resource.Attribute.radius = global::Sample.Droid.Resource.Attribute.radius;
			global::AndroidHUD.Resource.Attribute.rimColor = global::Sample.Droid.Resource.Attribute.rimColor;
			global::AndroidHUD.Resource.Attribute.rimWidth = global::Sample.Droid.Resource.Attribute.rimWidth;
			global::AndroidHUD.Resource.Attribute.spinSpeed = global::Sample.Droid.Resource.Attribute.spinSpeed;
			global::AndroidHUD.Resource.Attribute.text = global::Sample.Droid.Resource.Attribute.text;
			global::AndroidHUD.Resource.Attribute.textColor = global::Sample.Droid.Resource.Attribute.textColor;
			global::AndroidHUD.Resource.Attribute.textSize = global::Sample.Droid.Resource.Attribute.textSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::Sample.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::Sample.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::Sample.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::Sample.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::Sample.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::Sample.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::Sample.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::Sample.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::Sample.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::Sample.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::Sample.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::Sample.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::Sample.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_barColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_barColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_barLength = global::Sample.Droid.Resource.Styleable.ProgressWheel_barLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_barWidth = global::Sample.Droid.Resource.Styleable.ProgressWheel_barWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_circleColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_circleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_delayMillis = global::Sample.Droid.Resource.Styleable.ProgressWheel_delayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_radius = global::Sample.Droid.Resource.Styleable.ProgressWheel_radius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_rimColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_rimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_rimWidth = global::Sample.Droid.Resource.Styleable.ProgressWheel_rimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_spinSpeed = global::Sample.Droid.Resource.Styleable.ProgressWheel_spinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_text = global::Sample.Droid.Resource.Styleable.ProgressWheel_text;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_textColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_textColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_textSize = global::Sample.Droid.Resource.Styleable.ProgressWheel_textSize;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Sample.Droid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Sample.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Sample.Droid.Resource.Layout.zxingscannerfragmentlayout;
			global::Acr.MvvmCross.Plugins.BarCodeScanner.Droid.Resource.Id.contentFrame = global::Sample.Droid.Resource.Id.contentFrame;
			global::Acr.MvvmCross.Plugins.BarCodeScanner.Droid.Resource.Layout.zxingscanneractivitylayout = global::Sample.Droid.Resource.Layout.zxingscanneractivitylayout;
			global::Acr.MvvmCross.Plugins.BarCodeScanner.Droid.Resource.Layout.zxingscannerfragmentlayout = global::Sample.Droid.Resource.Layout.zxingscannerfragmentlayout;
			global::Acr.MvvmCross.Plugins.BarCodeScanner.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.BarCodeScanner.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.DeviceInfo.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.DeviceInfo.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.ExternalApp.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.ExternalApp.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.Network.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.Network.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.Settings.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.Settings.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.Storage.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.Storage.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.barColor = global::Sample.Droid.Resource.Attribute.barColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.barLength = global::Sample.Droid.Resource.Attribute.barLength;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.barWidth = global::Sample.Droid.Resource.Attribute.barWidth;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.circleColor = global::Sample.Droid.Resource.Attribute.circleColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.delayMillis = global::Sample.Droid.Resource.Attribute.delayMillis;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.radius = global::Sample.Droid.Resource.Attribute.radius;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.rimColor = global::Sample.Droid.Resource.Attribute.rimColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.rimWidth = global::Sample.Droid.Resource.Attribute.rimWidth;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.spinSpeed = global::Sample.Droid.Resource.Attribute.spinSpeed;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.text = global::Sample.Droid.Resource.Attribute.text;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.textColor = global::Sample.Droid.Resource.Attribute.textColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Attribute.textSize = global::Sample.Droid.Resource.Attribute.textSize;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Drawable.ic_errorstatus = global::Sample.Droid.Resource.Drawable.ic_errorstatus;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Drawable.ic_successstatus = global::Sample.Droid.Resource.Drawable.ic_successstatus;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Drawable.roundedbg = global::Sample.Droid.Resource.Drawable.roundedbg;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Drawable.roundedbgdark = global::Sample.Droid.Resource.Drawable.roundedbgdark;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Id.loadingImage = global::Sample.Droid.Resource.Id.loadingImage;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Id.loadingProgressBar = global::Sample.Droid.Resource.Id.loadingProgressBar;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Id.loadingProgressWheel = global::Sample.Droid.Resource.Id.loadingProgressWheel;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Id.textViewStatus = global::Sample.Droid.Resource.Id.textViewStatus;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Layout.loading = global::Sample.Droid.Resource.Layout.loading;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Layout.loadingimage = global::Sample.Droid.Resource.Layout.loadingimage;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Layout.loadingprogress = global::Sample.Droid.Resource.Layout.loadingprogress;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.String.library_name = global::Sample.Droid.Resource.String.library_name;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel = global::Sample.Droid.Resource.Styleable.ProgressWheel;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_barColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_barColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_barLength = global::Sample.Droid.Resource.Styleable.ProgressWheel_barLength;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_barWidth = global::Sample.Droid.Resource.Styleable.ProgressWheel_barWidth;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_circleColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_circleColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_delayMillis = global::Sample.Droid.Resource.Styleable.ProgressWheel_delayMillis;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_radius = global::Sample.Droid.Resource.Styleable.ProgressWheel_radius;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_rimColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_rimColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_rimWidth = global::Sample.Droid.Resource.Styleable.ProgressWheel_rimWidth;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_spinSpeed = global::Sample.Droid.Resource.Styleable.ProgressWheel_spinSpeed;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_text = global::Sample.Droid.Resource.Styleable.ProgressWheel_text;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_textColor = global::Sample.Droid.Resource.Styleable.ProgressWheel_textColor;
			global::Acr.MvvmCross.Plugins.UserDialogs.Droid.Resource.Styleable.ProgressWheel_textSize = global::Sample.Droid.Resource.Styleable.ProgressWheel_textSize;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000c
			public const int MvxBind = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int MvxDropDownItemTemplate = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int MvxItemTemplate = 2130771983;
			
			// aapt resource value: 0x7f01000d
			public const int MvxLang = 2130771981;
			
			// aapt resource value: 0x7f010011
			public const int MvxSource = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int MvxTemplate = 2130771982;
			
			// aapt resource value: 0x7f010003
			public const int barColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int barLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int barWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int circleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int delayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int radius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int rimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int rimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int spinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int text = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int textColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int textSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_errorstatus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_successstatus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int roundedbg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int roundedbgdark = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MvxBindingTagUnique = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int contentFrame = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int loadingImage = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int loadingProgressBar = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int loadingProgressWheel = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int textViewStatus = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int loading = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loadingimage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingprogress = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Splash = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int zxingscanneractivitylayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int zxingscannerfragmentlayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771980,
					2130771981};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771982};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771985};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_barColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_barLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_barWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_circleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_delayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_radius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_rimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_rimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_spinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_text = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_textColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_textSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
